### ISSUE TITLE
Check why one of the GTEx datasets in Fig. 3b has such a lot cell count

### ISSUE THREAD

**Issue by andreasbueckle** [x-atlas-consortia/hra-pop#12]
Dataset https://doi.org/10.1126/science.abl4290#GTEX-1CAMR-5015-SM-HPJ3B has only 40 cells: https://raw.githubusercontent.com/x-atlas-consortia/hra-pop/main/output-data/v0.5/reports/atlas/validation-v5.csv

That seems very low. @vickydaiya can you please investigate?

**Comment by vickydaiya** [comment]
Just checked. We split the GTEx data by Sample ID and this Sample ID has only 40 cells
