### ISSUE TITLE
Need data for new figure to visualize homogeneity and heterogeneity

### ISSUE THREAD

**Issue by andreasbueckle** [x-atlas-consortia/hra-pop#14]
Katy suggested a figure to visualize the homo-/heterogeneity of AS. x-axis: cosine sim (needs clarification). y-axis: number of datasets. Each dot is an AS. Color: whether the ```as-cell-summary``` was computed (aka is 3-diamond) or predicted via ```application-1``` or ```application-2```.

**Comment by andreasbueckle** [comment]
Update from discussion with @bherr2:
Note: this is experimental!!
It makes more sense to draw a faceted scatter graph, where each organ gets a scatter graph. Each dot is a as-as similarity for that organ. The x-axis is the cosine similarity between the two AS, the y-axis is the number of datasets in AS1, and size is the number of datasets for AS2. 

The data format would be:
```organ | as_1_label | as_2_label | cosine_sim | number_dataset_as_1 | number_dataset_as_2 

Alternatively: make a heatmap: https://r-graph-gallery.com/79-levelplot-with-ggplot2.html 

Adding predicted data to ```as-cell-summaries``` is out of scope for the paper but could be added in the future.

**Comment by andreasbueckle** [comment]
@bherr2 
It was suggested to only compute cosine similarities between ```cell_summaries``` made for ```sc_bulk``` and ```spatial```. Is this feasible for this issue? Might result in a small bucket, but comparing bulk to spatial may result in a muddled comparison. So, could we add a column ```annotation_method``` to each AS-AS link?

**Comment by bherr2** [comment]
Annotation method or modality?

**Comment by bherr2** [comment]
Actually, strike that, it is going to take some reworking to add.

**Comment by andreasbueckle** [comment]
```modality```. Although the atlas-as-cell-summaries list ```spatial``` as a ```annotation_method``` also: https://github.com/x-atlas-consortia/hra-pop/blob/main/output-data/v0.5/atlas-as-cell-summaries.jsonld#L5990

**Comment by bherr2** [comment]
If you are comparing sc_bulk to spatial, it is most definitely modality.

**Comment by bherr2** [comment]
figure-as-as-sim covers this. Close?
