### ISSUE TITLE
Write query to get Table 1

### ISSUE THREAD

**Issue by andreasbueckle** [x-atlas-consortia/hra-pop#33]
This table is for the main part of the CTPop paper and should show number of: 
 - studies
 - sex
 - donors 
 - organs
 - tissue blocks
 - tissue sections
 - datasets 
 - unique cell types
 - number of cells for that cell type

This should be broken out by: portal/source.

**Comment by bherr2** [comment]
New CSV available at: https://github.com/x-atlas-consortia/hra-pop/blob/main/output-data/v0.10.1/reports/atlas/table-1.csv

**Comment by andreasbueckle** [comment]
Bruce removes 
```ref_organ ccf:organ_owner_sex ?sex .```
 from queri for table-1

**Comment by bherr2** [comment]
Done
