### ISSUE TITLE
Document hra-pop queries in Markdown file

### ISSUE THREAD

**Issue by andreasbueckle** [x-atlas-consortia/hra-pop#50]
Can extract comments from SPARQL queries

**Comment by bherr2** [comment]
@andreasbueckle please review. It has been merged to main.

**Comment by andreasbueckle** [comment]
Thanks, reviewed it looks great! Added note to paper to point here and document. Closing this.

**Comment by andreasbueckle** [comment]
Done, see REPORTS.MD
