### ISSUE TITLE
Investigate publishing ```test-atlas-enriched-dataset-graph``` using DVC

### ISSUE THREAD

**Issue by andreasbueckle** [x-atlas-consortia/hra-pop#52]
```test-atlas-enriched-dataset-graph``` contains all datasets with extraction sites and/or cell summaries, "everything" incl. atlas and non-atlas.

**Comment by bherr2** [comment]
Now published here: https://cdn.humanatlas.io/dvc/hra-pop/raw-data/v0.5.1/test-atlas-enriched-dataset-graph.jsonld
