### ISSUE TITLE
Identify duplicate cells between secondary datasets in CxG

### ISSUE THREAD

**Issue by andreasbueckle** [x-atlas-consortia/hra-pop#59]
This is only an issue for the collection `b1a879f6-5638-48d3-8f64-f6592c1b1561`
 - @axdanbol investigates the extent of this issue
 - When this happens, it an error in the cell type annotation tools (all 3).
 - Need to evaluate new cell type counts after run v0.6.

**Comment by axdanbol** [comment]
Duplicate cells between secondary datasets are now filtered out during the download phase.
