### ISSUE TITLE
Compile overview of donor demographics for Universe

### ISSUE THREAD

**Issue by andreasbueckle** [x-atlas-consortia/hra-pop#67]
Could you please compile an overview/CSV file of donor demographics for the HRApop Universe across the four portals? This is to map how diverse the data used to build the hra-pop dataset currently is.

**Comment by bherr2** [comment]
https://github.com/x-atlas-consortia/hra-pop/blob/main/queries/universe-ad-hoc/donor-info.rq
=>
https://github.com/x-atlas-consortia/hra-pop/blob/main/output-data/v0.5.2/reports/universe-ad-hoc/donor-info.csv
