### ISSUE TITLE
From how many different collections do the hra-pop level CxG datasets come from? 

### ISSUE THREAD

**Issue by andreasbueckle** [x-atlas-consortia/hra-pop#69]

**Comment by bherr2** [comment]
https://github.com/x-atlas-consortia/hra-pop/blob/main/queries/atlas-ad-hoc/cxg-collections.rq
=>
https://github.com/x-atlas-consortia/hra-pop/blob/main/output-data/v0.5.2/reports/atlas-ad-hoc/cxg-collections.csv
