### ISSUE TITLE
As `as_label` to v2p1 query

### ISSUE THREAD

**Issue by andreasbueckle** [x-atlas-consortia/hra-pop#74]
@bherr2 
Any chance you can add `as_label` to https://github.com/x-atlas-consortia/hra-pop/blob/main/queries/atlas/validation-v2p1.rq? Makes visualizations easier to read.

**Comment by bherr2** [comment]
Fixed with HRApop v0.8.2
https://github.com/x-atlas-consortia/hra-pop/blob/main/output-data/v0.8.2/reports/atlas/validation-v2p1.csv
