### ISSUE TITLE
Make EUI for hra-pop atlas datasets

### ISSUE THREAD

**Issue by andreasbueckle** [x-atlas-consortia/hra-pop#78]
@bherr2 
Could we create an EUI for all the hra-pop atlas datasets/extraction sites? Possibly even include corridors? Otherwise, we can make a custom Unity viewer for the corridors if needed.

**Comment by bherr2** [comment]
Yes, it would be possible. Very easy for the rui locations (it's already in the right format). Corridors might take a little more work as I have not tested them.

**Comment by bherr2** [comment]
Added eui.html to the supporting information page here: https://cns-iu.github.io/hra-cell-type-populations-supporting-information/eui.html it pulls from the latest enriched rui locations available on hra-kg.

Screenshot:
![image](https://github.com/x-atlas-consortia/hra-pop/assets/34098595/1b7a4e55-4d04-4db6-82ef-b01426076165)

Adding corridors will take more time/effort

**Comment by andreasbueckle** [comment]
Thanks! Will link to this from companion website.
