### ISSUE TITLE
Need new corridors

### ISSUE THREAD

**Issue by andreasbueckle** [x-atlas-consortia/hra-pop#8]
Need to point Lu Chen to new resource to place new corridors, and which ```json-ld```file(s) to use.

**Comment by bherr2** [comment]
[full-dataset-graph.jsonld.zip](https://github.com/x-atlas-consortia/hra-pop/files/13620318/full-dataset-graph.jsonld.zip)

attached zipped rui-locations.jsonld style data file that has all the rui locations to compute corridors for. When done, create a PR with the corridors in a corridors folder in this repo.

**Comment by bherr2** [comment]
@LuchenCatherine updated rui locations to process are here:
[full-dataset-graph.jsonld.zip](https://github.com/x-atlas-consortia/hra-pop/files/13640937/full-dataset-graph.jsonld.zip)

**Comment by bherr2** [comment]
@LuchenCatherine for hra-pop v0.5.1 you can find the RUI locations here: https://cdn.humanatlas.io/digital-objects/ds-graph/hra-pop-full/v0.5.1/assets/full-dataset-graph.jsonld

**Comment by LuchenCatherine** [comment]
> @LuchenCatherine for hra-pop v0.5.1 you can find the RUI locations here: https://cdn.humanatlas.io/digital-objects/ds-graph/hra-pop-full/v0.5.1/assets/full-dataset-graph.jsonld

Sure. will use the latest RUI locations.

**Comment by andreasbueckle** [comment]
I copied the new corridors into ```/input-data/corridors``` and committed, made PR: https://github.com/x-atlas-consortia/hra-pop/pull/40

@bherr2 
I assume our next run (v0.6) will also fix #34 ?

**Comment by bherr2** [comment]
Yep

**Comment by andreasbueckle** [comment]
Fixed with #40
