### ISSUE TITLE
One more report for AS and CT pairs

### ISSUE THREAD

**Issue by andreasbueckle** [x-atlas-consortia/hra-pop#83]
Need data similar to https://github.com/x-atlas-consortia/hra-pop/blob/main/output-data/v0.10.1/reports/atlas/validation-v5.csv: 

Same columns but `as_id` (UBERON) and `as-label`

Goal: make the below but for AS in organs (heart and large/small intestine at first):
![SI-fig2a-hrapop-heatmap_azimuth-cte](https://github.com/x-atlas-consortia/hra-pop/assets/22821046/ea1df2be-1541-4fc0-b96a-8f5322483096)

**Comment by bherr2** [comment]
Columns: `tool,modality,organ,organId,as,as_id,as3d_id,sex,cell_id,cell_label,cell_count,percentage`

**Comment by andreasbueckle** [comment]
New CSV now available at: https://github.com/x-atlas-consortia/hra-pop/blob/main/output-data/v0.10.1/reports/atlas/validation-v6.csv

**Comment by andreasbueckle** [comment]
@bherr2 removes `as_3d_id` to avoid near-duplications.

**Comment by bherr2** [comment]
Done
