### ISSUE TITLE
Need unique list of assay types in 9223 universe datasets

### ISSUE THREAD

**Issue by andreasbueckle** [x-atlas-consortia/hra-pop#84]

**Comment by bherr2** [comment]
https://github.com/x-atlas-consortia/hra-pop/blob/723d6c3dd91b25a9d1a916cacc4fa294218eae01/output-data/v0.10.1/reports/atlas-ad-hoc/messy-assay-types.csv

**Comment by bherr2** [comment]
If we ever need something less messy, create a new issue (after June 14th 😆). Closing as completed.
