### ISSUE TITLE
Query for UBERON IDs and HRA DOs

### ISSUE THREAD

**Issue by andreasbueckle** [x-atlas-consortia/hra-pop#86]
We would like to request a SPARQL query over the UBERON IDs in the left column from the table below that indicate:

`UBERON_ID | has_3d_reference_object | has_asct_b_table | has_parent_uberon_in_with_3d_reference_object | has_parent_with_asct_b_table | parent_uberon_id`

The last 3 columns only if cols 2 and/or 3 are FALSE.

SMTSDUBRID | SMTSDUBRTRM
-- | --
UBERON:0005406 | Perirenal fat
UBERON:0002190 | subcutaneous adipose tissue
UBERON:0002190 | subcutaneous adipose tissue
UBERON:0002190 | subcutaneous adipose tissue
UBERON:0001234 | left adrenal gland
UBERON:0001516 | abdominal aorta
UBERON:0001416 | ascending aorta
UBERON:0002345 | descending thoracic aorta?
UBERON:0001626 | coronary artery
UBERON:0001626 | coronary artery
UBERON:0002887 | basal amygdaloid nucleus
UBERON:0001873 | caudate nucleus
UBERON:0004002 | posterior lobe of cerebellum
UBERON:0009834 | dorsolateral prefrontal cortex
UBERON:0002728 | entorhinal cortex
UBERON:0003881 | CA1 field of hippocampus
UBERON:0001885 | dentate gyrus of hippocampal formation
UBERON:0002751 | inferior temporal gyrus
UBERON:0000451, UBERON:0009835 | prefrontal cortex, anterior cingulate cortex
UBERON:0002739 | medial dorsal nucleus of thalamus
UBERON:0002264 | olfactory bulb
UBERON:0004167 | orbitofrontal cortex
UBERON:0034751 | primary auditory cortex
UBERON:0001384 | primary motor cortex
UBERON:0008933 | primary somatosensory cortex
UBERON:0002436 | primary visual cortex
UBERON:0001874 | putamen
UBERON:0005844 | spinal cord segment
UBERON:0002038 | substantia nigra
UBERON:0000955 | Whole brain annotation
UBERON:0002178 | Left main bronchus
UBERON:0001156 | ascending colon
UBERON:0001159 | sigmoid colon
UBERON:0002363 | falx cerebri
UBERON:0013473 | lower esophagus
UBERON:0002094 | interventricular septum
UBERON:0002094 | interventricular septum
UBERON:0003380 | cardiac muscle of left atrium
UBERON:0003382 | cardiac muscle of left ventricle
UBERON:0003382 | cardiac muscle of left ventricle
UBERON:0003379 | cardiac muscle of right atrium
UBERON:0003381 | cardiac muscle of right ventricle
UBERON:0003381 | cardiac muscle of right ventricle
UBERON:0000948 | heart
UBERON:0001225; UBERON:8410073 | cortex of kidney; medullary region of kidney
UBERON:0001117 | caudate lobe of liver
UBERON:0001114 | right lobe of liver
UBERON:0008953 | lower lobe of left lung
UBERON:0008952 | upper lobe of left lung
UBERON:0008952 | upper lobe of left lung
UBERON:0008952 | upper lobe of left lung
UBERON:0002171 | lower lobe of right lung
UBERON:0002174 | middle lobe of right lung
UBERON:0002170 | upper lobe of right lung
UBERON:0039167 | bronchopulmonary lymph node
UBERON:0002509 | mesenteric lymph node
UBERON:8480055 | subcarinal lymph node
UBERON:0001388 | gastrocnemius
UBERON:0001377 | quadriceps femoris
UBERON:0001322 | sciatic nerve
UBERON:0000992 | ovary
UBERON:0001264 | pancreas
UBERON:0000007 | pituitary gland
UBERON:0015474 | axilla skin
uberon - 8480050 | skin of calf
UBERON:0002114 | duodenum
UBERON:0002115 | jejunum
UBERON:0002116 | ileum
UBERON:0002106 | spleen
UBERON:0000945 | stomach
UBERON:0000473 | testis
UBERON:0002046 | thyroid gland
UBERON:0003126 | trachea
UBERON:0000995 | uterus
CL:0000738 | leukocyte
UBERON:0000178 | blood

**Comment by bherr2** [comment]
This is out of scope for HRApop in general, but I went ahead and created the query and here's the yasgui link that has the query and the results: <https://api.triplydb.com/s/m7WpZ5j4W>

**Comment by andreasbueckle** [comment]
@bherr2 
Thanks! I know it's out of scope, just did not know where to out the issue. Feel free to transfer elsewhere if appropriate.
