### ISSUE TITLE
Need new 3D positions for cells

### ISSUE THREAD

**Issue by andreasbueckle** [x-atlas-consortia/hra-pop#9]
@LuchenCatherine
Let's use those 2 again:

 - https://github.com/x-atlas-consortia/hra-pop/blob/main/output-data/v0.5/atlas-as-cell-summaries.jsonld#L1819-L1820
 - https://github.com/x-atlas-consortia/hra-pop/blob/main/output-data/v0.5/atlas-as-cell-summaries.jsonld#L1355-L1356

3D Reference Object: male, left kidney at https://humanatlas.io/3d-reference-library?version=1.4&organ=Kidney 

from @bherr2:
Please commit those to a new sub-folder this folder: https://github.com/cns-iu/hra-cell-type-populations-supporting-information/tree/main/deprecated-data

Please call it ```3d_cell_positions_v0.5```
```as_label | uberon_id | cell_label | cell_id | x | y | z```

**Comment by andreasbueckle** [comment]
@LuchenCatherine 
Let's use those 2 again:
 - https://github.com/x-atlas-consortia/hra-pop/blob/main/output-data/v0.5/atlas-as-cell-summaries.jsonld#L1819-L1820
 - https://github.com/x-atlas-consortia/hra-pop/blob/main/output-data/v0.5/atlas-as-cell-summaries.jsonld#L1355-L1356

**Comment by bherr2** [comment]
Put cells csv into the supporting information page for now

**Comment by andreasbueckle** [comment]
PS @LuchenCatherine 
We also need 3D cells for one of the corridors that intersects with both AS. Let's discuss via Slack.

**Comment by andreasbueckle** [comment]
PS @LuchenCatherine 
And cell types for renal pyramid B and H.

**Comment by LuchenCatherine** [comment]
Use rui_location @id "http://purl.org/ccf/1.5/f3f2fabb-6802-4fd4-920e-1914293db252" for demonstration. 
"rui_location": {
            "@id": "http://purl.org/ccf/1.5/f3f2fabb-6802-4fd4-920e-1914293db252",
            "@type": "SpatialEntity",
            "ccf_annotations": [
              "http://purl.obolibrary.org/obo/UBERON_0002015",
              "http://purl.obolibrary.org/obo/UBERON_0001225",
              "http://purl.obolibrary.org/obo/UBERON_0002189",
              "http://purl.obolibrary.org/obo/UBERON_0001284",
              "http://purl.obolibrary.org/obo/UBERON_0000362",
              "http://purl.obolibrary.org/obo/UBERON_0004200"
            ],
            "creation_date": "2022-06-10",
            "creator": "Amanda Knoten",
            "creator_first_name": "Amanda",
            "creator_last_name": "Knoten",
            "dimension_units": "millimeter",
            "placement": {
              "@id": "http://purl.org/ccf/1.5/f3f2fabb-6802-4fd4-920e-1914293db252_placement",
              "@type": "SpatialPlacement",
              "placement_date": "2022-06-10",
              "rotation_order": "XYZ",
              "rotation_units": "degree",
              "scaling_units": "ratio",
              "target": "http://purl.org/ccf/latest/ccf.owl#VHMLeftKidney",
              "translation_units": "millimeter",
              "x_rotation": -39,
              "x_scaling": 1,
              "x_translation": 15.443,
              "y_rotation": -41,
              "y_scaling": 1,
              "y_translation": 93.931,
              "z_rotation": 0,
              "z_scaling": 1,
              "z_translation": 33.215
            },
            "x_dimension": 2,
            "y_dimension": 10,
            "z_dimension": 2,
            "ctpop:rui_location_source_url": "https://ccf-api.hubmapconsortium.org/v1/hubmap/rui_locations.jsonld"
          }

**Comment by LuchenCatherine** [comment]
> PS @LuchenCatherine And cell types for renal pyramid B and H.

Will generate cells for VH_M_renal_pyramid_L_b and VH_M_renal_pyramid_L_h

**Comment by LuchenCatherine** [comment]
Generated 1% cells for  VH_M_renal_pyramid_L_a, VH_M_outer_cortex_of_kidney_L, VH_M_renal_pyramid_L_b, VH_M_renal_pyramid_L_h. Please check https://github.com/cns-iu/hra-cell-type-populations-supporting-information/blob/main/deprecated-data/cell-locations/cell_locations_hrapop_VH_M_kidney_L.csv

**Comment by andreasbueckle** [comment]
@LuchenCatherine 
Could we get cell-type population for these AS instead? These are the ones that Ushma, Katy, and I agreed on eventually:
Renal pyramid: https://github.com/x-atlas-consortia/hra-pop/blob/main/output-data/v0.5/atlas-as-cell-summaries.jsonld#L1356
https://github.com/x-atlas-consortia/hra-pop/blob/main/output-data/v0.5/atlas-as-cell-summaries.jsonld#L20355

**Comment by andreasbueckle** [comment]
Will be solved with https://github.com/hubmapconsortium/hra-glb-mesh-collisions
